# Generated by Django 3.2.11 on 2022-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryStatistic',
            fields=[
                ('slug', models.SlugField(default='default', max_length=100, primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=100)),
                ('files_and_dirs', models.JSONField()),
                ('number_of_files', models.IntegerField()),
                ('most_recent_word', models.CharField(max_length=100)),
                ('least_recent_word', models.CharField(max_length=100)),
                ('average_word_length', models.FloatField()),
                ('vowels', models.JSONField()),
                ('consonants', models.JSONField()),
                ('syllables', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='FileStatistic',
            fields=[
                ('slug', models.SlugField(default='default', max_length=100, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('most_recent_word', models.CharField(max_length=1000)),
                ('least_recent_word', models.CharField(max_length=1000)),
                ('average_word_length', models.FloatField()),
                ('vowels', models.JSONField()),
                ('consonants', models.JSONField()),
                ('syllables', models.JSONField(default={})),
            ],
        ),
    ]
