# Generated by Django 3.2.11 on 2022-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorystatistic',
            name='syllables',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='filestatistic',
            name='syllables',
            field=models.JSONField(default=dict),
        ),
    ]
